services:
  generate-autodoc:
    build:
      context: ./edge-functions/generate-autodoc
      dockerfile: Dockerfile
    container_name: generate-autodoc
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -s -o /dev/null -w '%{http_code}' http://localhost:8080 | grep -E '200|405'"]
      interval: 30s
      timeout: 10s
      retries: 3
  merge-autodoc:
    build:
      context: ./edge-functions/merge-autodoc
      dockerfile: Dockerfile
    container_name: merge-autodoc
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -s -o /dev/null -w '%{http_code}' http://localhost:8080 | grep -E '200|405'"]
      interval: 30s
      timeout: 10s
      retries: 3
  explode-autodoc:
    build:
      context: ./edge-functions/explode-autodoc
      dockerfile: Dockerfile
    container_name: explode-autodoc
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -s -o /dev/null -w '%{http_code}' http://localhost:8080 | grep -E '200|405'"]
      interval: 30s
      timeout: 10s
      retries: 3
